### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by aditya1906**

### CODE REVIEW

**Comment by aditya1906** [comment]
@mattonit what are your thoughts on these changes?

**Comment by mattonit** [comment]
Thank you for contributing! I think we can merge it ;)

**Comment by aditya1906** [comment]
Thanks great. Happy to contribute :-)

**Comment by mateuszlubianka1993** [comment]
@cla-bot check

**Comment by mateuszlubianka1993** [comment]
@cla-bot check

**Pull request closed without merging**
