### PR TITLE
Remove Duplicate code

### PR DESCRIPTION
**Pull request by aditya1906**
Hi, there has been a ton of duplicate code in some of the scss files. I tried my best to remove the duplicate code. And number of lines are reduced. How these changes can help a lot. :-)

### CODE REVIEW

**Comment by mattonit** [comment]
I think we can merge it. @pglejzer can you review these changes?

**Comment by aditya1906** [comment]
Thanks @mattonit for appreciating my contribution.

**Comment by mattonit** [comment]
Thank you @aditya1906 for contributing!

**Comment by aditya1906** [comment]
@mattonit Its my pleasure

**Pull request merged**
