### PR TITLE
fix SASS issue: incompatible units 'px' and 'rem'

### PR DESCRIPTION
**Pull request by ryanrishi**
- convert most variables from px → rem
- update variables-b4 to be in sync with [twbs/bootstrap#v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev)

There's an issue when pointing to the latest v4-dev, since Bootstrap defines its variables in `rem`. This PR fixes that.

### CODE REVIEW

**Comment by phpeek** [comment]
@ryanrishi This is awesome ! I've started to fix it myself, but found Your PR instead.

Now using:

```sass
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

@import "~mdbootstrap/sass/mdb/free/data/functions";
@import "~mdbootstrap/sass/mdb/free/data/variables-b4";

...
```

is working like a charm.

Hope this would be merged. :)

**Comment by mgebundy** [comment]
Was having this issue in 4.4.4, overrode the variable causing issue before importing the package like so:

```
$popover-arrow-outer-width: (17/16)rem; 
```

**Comment by mateuszlubianka1993** [comment]
@cla-bot check

**Comment by gbujanski** [comment]
old PR and outdated

**Pull request closed without merging**
