### PR TITLE
Correct line endings to LF only

### LINKED ISSUE #215: Git complaining about line endings in SVG files
The SVG files in the img/svg directory have CRLF line endings which git always replaces with LFs only. When using these files in your own project where you commit the assets as well, you always get complaints from git at the command line.

Is it possible to cleanup those files and deliver them with LFs only?

### PR DESCRIPTION
**Pull request by jurgenhaas**
This fixes #215

### CODE REVIEW

**Comment by mateuszlubianka1993** [comment]
@cla-bot check

**Comment by jurgenhaas** [comment]
I have filled the form yesterday, is there anything else I need to do in order to get this check repeated?

**Comment by mateuszlubianka1993** [comment]
@cla-bot check

**Comment by gbujanski** [comment]
old and outdated PR

**Pull request closed without merging**
